### ISSUE TITLE
Remake the installer to AVG Standards

### ISSUE THREAD

**Issue by BobbyGR** [BobbyGR/AIOMiner#101]
AVG will not de-shit lust us until we meet their standards. 

https://support.avg.com/SupportArticleView?l=en&urlName=AVG-clean-guidelines&q=Hide+My+Ass+HMA+VPN+FAQ&supportType=home#idt_200

This has taken priority over all other projects

**Comment by BobbyGR** [comment]
Being more transparent on what we install.
https://aiominer.com/software/

**Comment by BobbyGR** [comment]
Uploaded latest installer to AVG for approval.  pending answer

**Comment by BobbyGR** [comment]
Hello,

Thank you for your email.

Unfortunately, your setup does not match our clean guidelines. 
e.g.
- Uninstallation through standard API is not possible
- Wording "Fix" in Red colored button is pressuring user

Best regards,
AVG Customer Care

**Comment by BobbyGR** [comment]
Fix buttons were turned to Purple.

**Comment by Rawbrekt** [comment]
"Wording "Fix" in Red colored button is pressuring user"
Oh my, I feel for you

**Comment by BobbyGR** [comment]
Got an email this morning.

Hello,

Thank you for contacting AVG.

Please accept our apologies for the inconvenience caused. The detection by AVG was incorrect and was removed in a recent AVG update, please wait at least 24 hours.

If the detection persists, please reply to this e-mail and:

1. Attach a screenshot of your virus database version in AVG.

Open AVG ▸ Menu ▸ About
2. Attach the screenshot including the detection dialog, with See details in the bottom-right corner displayed. To create a screenshot, please refer to the following link.

Creating a screenshot
Please do not hesitate to contact AVG at any time with further inquiries.

Thank you for your patience and cooperation, we appreciate it.

Best regards,

AVG Customer Care
