### ISSUE TITLE
Just stops 

### ISSUE THREAD

**Issue by gator6615** [BobbyGR/AIOMiner#111]
18:14:30 Miner:    Error ******** GPU[01]:  CudaError: 702 at position 400
18:14:30 Miner:    Error ******** All GPUs are disabled. TT-Miner cannot continue and will exit now
18:14:30 Miner:    Error ******** GPU[00]:  CudaError: 702 at position 402
18:14:30 Miner:    Error ******** All GPUs are disabled. TT-Miner cannot continue and will exit now

Also the download updates freezes

**Comment by BobbyGR** [comment]
Correct, at this time the install won't work and the app will not run until we find a host for the mining files.  ideally someone would want to do this to help out with the project, but here we are!

**Comment by drxeno02** [comment]
How to host the project? Maybe I can help. What are costs?

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by BobbyGR** [comment]
Aquired hosting, files going up shortly along with latest build
