### ISSUE TITLE
Limited Pool Options

### ISSUE THREAD

**Issue by m-henderson** [BobbyGR/AIOMiner#117]
I downloaded AIO miner and ran it as I was following along with this video: https://www.youtube.com/watch?v=iq5W3id0Kxw 
When I go to Pool/Coin Settings I am only presented with ethereum as an option. 

![image](https://user-images.githubusercontent.com/16070192/103288431-73bd8400-49aa-11eb-9b8c-7b6a5d79c82b.png)

Is there something I am doing wrong? 
Thanks, 
Mike

**Comment by drxeno02** [comment]
@m-henderson Hey Michael! You can add any miner and mine any coin (pretty much). The Etherium is just one default setting to give you an example and get you rolling. 

If you want to mine other coins, just input different information, test your pool, then checkbox that "Primary Pool" option and save. What coin are you looking to mine? Maybe I can help you with the IP/Port? This information is usually provided to you on the miner site which you are planning to use.

**Comment by BobbyGR** [comment]
This is correct.  With the release of AIOMiner to the public for open source, only ethereum (ethash) algo was provided.  I have recently provided steps on adding in your own mining application on the readme.
