### ISSUE TITLE
AIO Monitor doesn't work as expected

### ISSUE THREAD

**Issue by Irwenzhao** [BobbyGR/AIOMiner#15]
although I can reproduce what I'm reporting, I don't have other rigs to test on so this probably require more testings, etc.

to my understanding, the miner will be automatically restarted if an error is detected, however, this is not the case in my testings.

case 1: I manually close the miner, AIO Monitor status is still green, restart countdown is still 5. To clarify, I don't know if the miner is designed to restart in this case, and have no idea if it's working as intended. If it is, I feel that it should be restarted when I close it since there's a big "stop" button if I really want to stop mining

steps to reproduce:
1. set up a pool for MonaCoin (in my case)
2. start the miner and wait for hashrates to stabilize
3. close the ccminer command prompt

expected outcome: mining status becomes red, restart countdown drops to 4, miner is restarted
real outcome: mining status stays green, restart countdown stays at 5, miner is not restarted

case 2: this case simulates a legitimate crash in the miner by using another miner (of another algo) alongside the AIO miner since the two cannot work alongside one another, but two mining instances of the same algo can. in a real world scenario, nobody (should and) will run two instances of two different algorithms and these crashes would not occur, but for testing sake this is done.

prerequisites:
- an external miner (Claymore v10.2 configured for ETH in my case)

steps to reproduce:
1. set up a pool for MonaCoin (in my case)
2. start the miner and wait for hashrates to stabilize
3. start Claymore and wait for crash

expected outcome: display driver crashes, both Claymore and ccminer spits out errors, Claymore auto-restarts, mining status becomes red, restart countdown drops to 4, ccminer is restarted
real outcome: display driver crashes, both Claymore and ccminer spits out errors, Claymore auto-restarts, mining status stays green, restart countdown stays at 5, ccminer is not restarted

EDIT 1: miner crashed by itself, didn't get email nor did it restart on its own.

**Comment by BobbyGR** [comment]
Nice write up, thank you.  I'll fix asap.  That is what is intended.

**Comment by BobbyGR** [comment]
As for case 2, I'll put in a Check.  Thanks again

**Comment by BobbyGR** [comment]
Both issues have been resolved, please download the Alpha 6  HP1.rar, unless you have removed the app all together then download the larger WHP1.rar

**Comment by Irwenzhao** [comment]
so with the new version there's a new pop up saying "okhere".

here are a couple of issues I've gotten:

Case 1: I manually close the miner.
What happens: nothing
steps I took next:
1. I clicked the ok button in the okhere window, mining status turns red, restart countdown goes to 4, miner starts up again
2. the okhere window pops up again, I click it. mining status goes green, restart countdown goes back up to 5

conclusions: restarting of miner is not automatic and I can make the restart countdown go back up to 5 by just clicking ok in the okhere window

case 2: same as before. miner not restarted, okhere window unable to detect error, miner not restarted.

conclusions: same as case 1

case 3: with the new okhere window, I found this loophole that would allow you to start the miner while AIOMiner is not running. here's the steps to reproduce it

1. set up a pool for MonaCoin (in my case)
2. start the miner, wait for hashrates to stabilize and wait for the okhere window to pop up
3. manually close ccminer
4. click the ok button in the okhere window, then immediately click stop in the AIOMiner GUI

**Comment by BobbyGR** [comment]
damn it..

**Comment by BobbyGR** [comment]
--HOT PATCH 2 ---

Fixed the "OKHERE" from "hotpatch1"
Can only get better from here right?

**Comment by BobbyGR** [comment]
Also, this is the kind of reason why I need more testers.  If you ever join the discord (or if you already are an alpha tester) thank you!

**Comment by BobbyGR** [comment]
Assuming this is good to go and closing out
