### ISSUE TITLE
delete pool button deletes all pools

### ISSUE THREAD

**Issue by ianthera** [BobbyGR/AIOMiner#16]
if you create a pool before then add another one and delete the first one, it deletes all the pools in the list. not the selected one.

**Comment by BobbyGR** [comment]
Go back and select another coin, then go to that coin.  It didn't delete it, just a bad refresh :)

**Comment by BobbyGR** [comment]
This issue was resolved in the upcoming release,  I was making a call to clear the pools then clear all of the text where clearing all of the text cleared the pools...so i've got hat going for me  :)
