### ISSUE TITLE
Installer.  Defender hates it

### ISSUE THREAD

**Issue by BobbyGR** [BobbyGR/AIOMiner#23]
Create a Windows 10 super anti virus equipped machine and see how you can install without them yelling.  It's mining software so I get it..but the installer is simple

**Comment by BobbyGR** [comment]
I submitted this installer to Windows Defender.  They gave it the clear and now it's good to go.

**Comment by drxeno02** [comment]
@BobbyGR Are you also working on trying to get any of the browsers to acknowledge Riskware (such as AIOMiner) and not treat it like Malware? With Firebase you can override the initial block and warning, but it is still pretty annoying. To be able to freely download will ease a lot of doubt and fear for newbie miners.
