### ISSUE TITLE
The specified executable is not a valid application for this OS platform.

### ISSUE THREAD

**Issue by jsaltzman** [BobbyGR/AIOMiner#25]
I tried to install AIOminer (whatever the current version is) and I got the following error:
![image](https://user-images.githubusercontent.com/2000982/34917607-c92cf796-f916-11e7-9798-2cd939d6a9c5.png)

**Comment by BobbyGR** [comment]
We had some server issues and dns issues.  Could take up to 24 hours for this to resolve.

**Comment by BobbyGR** [comment]
We had some server issues and dns issues.  Could take up to 24 hours for this to resolve.  

Download the .zip here to bypass until it's resolved.  http://45.58.56.144/products/AIO/A007/AIOMiner_A007.zip

**Comment by BobbyGR** [comment]
Looks as if the DNS issue is resolved and this should be back to working as "normal".  Will leave this open for a day just to confirm.

**Comment by jsaltzman** [comment]
I'm having the same issue.

**Comment by BobbyGR** [comment]
jsaltzman - What do you see when you goto AIOMINER.COM?

**Comment by jsaltzman** [comment]
This site cant be reached on google chrome.

**Comment by BobbyGR** [comment]
Guess it's going to take time for this...  you could try from command line, ipconfig /flushdns   curious if that helps any?

**Comment by jsaltzman** [comment]
Same issue after /flushdns.  Also, I tried to run the zip and when I open the pools settings I get an error (Im assuming it's caused by the same thing).

**Comment by BobbyGR** [comment]
Yup....bad day. For some reason it just got flushed again.  might be time to find a new VPS provider. they are doing things just to be doing them at this point. thanks for checking up on it.  ill ping back when it should be in the clear.  If anything it let's me know where I need to put in a few redundancy

**Comment by BobbyGR** [comment]
Moved DNS.  Things seem to be good now.  Please confirm when you can

**Comment by BobbyGR** [comment]
Should be good, others seem good :)
