### ISSUE TITLE
AIOMiner remote control

### ISSUE THREAD

**Issue by tzapu** [BobbyGR/AIOMiner#28]
Hi,
Thanks for this, it really eased my way into mining.

Is there any chance of some web interface/api/webhooks ?

I d like to be able to open an url and have aio start/stop

Would make remote controlling easier.

The idle check seems to consider the computer idle and start mining when in stea
Cheers

**Comment by BobbyGR** [comment]
Yes.  Working on a website with api access for users to manage allthethings.jpg

**Comment by tzapu** [comment]
nice one... any alpha access ?

thanks for everything 👍

**Comment by BobbyGR** [comment]
Heh, everything is alpha right now.  But focus is on AIO 8 right now.  Then website.  Hoping by AIO9/10 we will have website api access for people.  Making everything free makes it hard to buy stuff :) Wife will give me stinkeye ;)

**Comment by BobbyGR** [comment]
Started to review the SignalR package for this setup.  Seems like it can do everything we need it to do.  But will keep that open for discussion.

**Comment by BobbyGR** [comment]
Building API and react frontend to handle this.  Will go out with release 9

**Comment by BobbyGR** [comment]
Multiple rigs are testing on the website right now.  Stop/Start/Restart/Shutdown/Change Mining/Add Pool are working.

**Comment by BobbyGR** [comment]
Buttoning up, projected release 10/26/2018

**Comment by BobbyGR** [comment]
Release in a few hours.  testing is good.  closing this out
