### ISSUE TITLE
Not All GPU'S Mining

### ISSUE THREAD

**Issue by adam-g-100** [BobbyGR/AIOMiner#32]
![miner](https://user-images.githubusercontent.com/4473859/36351340-fecdf93a-14b0-11e8-9161-612432de474c.PNG)

Having a strange issue mining zen not all gpu's are mining if i close the miner and re-open it then those cards not mining will mine and the ones that were mining will not mine anymore.

Using 6 RX580
Driver installed is the AMD blockchain driver.

**Comment by BobbyGR** [comment]
Trying to follow here.  That's...interesting.  Go to your pool fore this.  Goto Advanced Settings.  Copy from current.  delete --devices 01234567 , hit continue, hit save.  Then try

**Comment by BobbyGR** [comment]
Did this help?

**Comment by adam-g-100** [comment]
Hi

Sorry for not. Getting back sooner.

I have recently switched to SMOS so I'm not sure if that fix worked. I guess you can close this until some has the same issue

Thanks for the help

Sent from my Xperia™ by Sony smartphone


---- Bobby G Roberts wrote ----


Did this help?
