### ISSUE TITLE
VEGA & FRONTIER blockchain drivers August 2017?

### ISSUE THREAD

**Issue by BitCoinJedi** [BobbyGR/AIOMiner#33]
Will you guys be able to optimize vega drivers to get these beasts running at full potential?
I've been messing around a ton almost 2 months and I can tap the touted 43 MH/s or 2200 H/s on crypto night etc... :(

**Comment by BobbyGR** [comment]
Vega and FE seem to be in a constant state of "alpha" drivers.  I don't know what we can do on our side of the fence to make this better.  Just make sure you check out CastXMR as that seems to be the best fro Vega/FE

**Comment by BobbyGR** [comment]
No way that I can see how we can do what is requested at this time
