### ISSUE TITLE
AIO Miner craash while mining snowgem

### ISSUE THREAD

**Issue by blueisash** [BobbyGR/AIOMiner#42]
Hi, I  amusing AIO miner to mine Snowgem. The test pool is running successful with all available pools. The miner throws error in the log sheet with restart immediately happening. I am using Nvdia gtx1050i on Win 10 OS.
[logreport.docx](https://github.com/BobbyGR/AIOMiner/files/1978196/logreport.docx)

**Comment by BobbyGR** [comment]
While the test of a pool is to confirm a few things, it's not very smart.  Confirm your wallet address.  Feel free to join the discord and we can run through it.

**Comment by blueisash** [comment]
My wallet address is **s1aAqDZkZKtAruSGV7dJBCFE3mgyaJPQ9PD**.  **Let me know the discord link** or join mine at https://discord.gg/rFhQHUv

**Comment by BobbyGR** [comment]
Any update?

**Comment by BobbyGR** [comment]
Closing for now.
