### ISSUE TITLE
Run ETHlargementPill without disabling UAC

### ISSUE THREAD

**Issue by xbkingx** [BobbyGR/AIOMiner#45]
Trying AIO for the first time and the idea of disabling UAC for the entire system did not sound like an acceptable solution.

You can get around the prompt by creating an elevated task in the task scheduler, as described here: https://winaero.com/blog/create-elevated-shortcut-to-skip-uac-prompt-in-windows-10/

I tried this and it does work. The easy way to test this is use Winaero Tweaker (free, no affiliation) and make an elevated shortcut, then look at the shortcut properties and task scheduler. You should be able to add the task at install time.

You'll see several cmds open briefly and close, but the end result is the same (no extra conhosts or anything to clean up and process call structure preserved - procexplorer shows conhost child of ETHlargement, which is a child of explorer).

**Comment by BobbyGR** [comment]
It's been a year, closing this one out
