### ISSUE TITLE
Bug (minor): Installer only shows Public Documents folder

### ISSUE THREAD

**Issue by xbkingx** [BobbyGR/AIOMiner#46]
At install, I'm only presented with the Public Documents folder during install location selection.  The tree structure below is visible, but not above, and there's no button to bring up a simple modal directory selection. Manually entering a path outside Public Documents works fine.

AIOMiner a8.1.1
Win10x64 1803

**Comment by BobbyGR** [comment]
![image](https://user-images.githubusercontent.com/16457262/42043456-7f53018a-7ac4-11e8-8b52-9e543d3def3d.png)

**Comment by BobbyGR** [comment]
Updating now, thank you

**Comment by BobbyGR** [comment]
Like all of our other products, the new installer will be tossing through the ringer with MS

aioinstaller.exeSubmission ID: 25c6ed8b-b5c8-4f48-94d5-b4365840c746 Status: Submitted Submitted by: XXXX.XXXXr@gmail.com Submitted: Jun 28, 2018 11:17:10 AM User Opinion: Incorrect detection Analyst comments:
No analyst comment provided.
