### ISSUE TITLE
Request: Prompt to add AIOMiner directory to Windows Defender exclusions

### ISSUE THREAD

**Issue by xbkingx** [BobbyGR/AIOMiner#47]
It would probably save you some headaches in the long run, but get consent because other nasty software could take advantage of this blind spot.

Add-MpPreference -ExclusionPath (path)
https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/configure-extension-file-exclusions-windows-defender-antivirus

Ideally, you'd store all non-configuration files under one directory and regularly check that the folder contents aren't manipulated, but just making the user aware should be fine in the short term.

**Comment by BobbyGR** [comment]
We will go ahead and add a checkmark that is there by default, but, good idea.
