### ISSUE TITLE
TestPool fails to run

### ISSUE THREAD

**Issue by lour441** [BobbyGR/AIOMiner#52]
TestPool fails with 
Value cannot be null.
Parameter name: hostname

![image](https://user-images.githubusercontent.com/11727941/41812576-75b31216-76da-11e8-9f1a-0612136421aa.png)

**Comment by BobbyGR** [comment]
With the fix that went in with the stratum+tcp:// and http/s:// it seems now you can only test pools that use them now or you will get this error.  Fixed one thing, broke another.  Fix will be in the next release.

**Comment by BobbyGR** [comment]
Fixed for 8.2.1

**Comment by BobbyGR** [comment]
8.2.1 released
