### ISSUE TITLE
AIOMiner GUI does not display correctly at start up.

### ISSUE THREAD

**Issue by lour441** [BobbyGR/AIOMiner#53]
When you have your rig set up to auto login and auto start AIOMiner, AOIMiner gui displays about 3/4 of the size that is should.  Half of the top 5 and GPU stats are cutoff.  The window is unable to be resized (this is a separate issue).  The work around is to close AIOMiner and restart it.  It displays correctly at that point.

![image](https://user-images.githubusercontent.com/11727941/41820298-8fd0f91a-779d-11e8-9d10-ab714828a99b.png)

**Comment by BobbyGR** [comment]
I'll see if I can duplicate, this is a fun and new one.

**Comment by BobbyGR** [comment]
Unable to duplicate, but I made it sizeable, so that might help?

**Comment by BobbyGR** [comment]
8.2.1 released, let me know if this helps with this
