### ISSUE TITLE
Project AIO-Lite

### ISSUE THREAD

**Issue by BobbyGR** [BobbyGR/AIOMiner#67]
- Algo Specific miners (AIO-Cryptonight, AIO-NeoSscrypt, etc,etc)
- Fast profit switching (Difficulty, Coin Estimate Count, Price Prediction)
- Fast Wallet setup
- E-Mail Alerts
- Hourly Stats
- Online Review
- Online wallets
- 2%~ Fee (Coins that advertise AIOMiner/AIO-Lite will have the option for 1% of that fee to be donated to them, if the users is mining their coin)
- Auto-Selling (Integrate API's for Exchanges)

**Comment by shanearcuri** [comment]
Leaderboards would be cool!
- Highest hashrate for [Insert GPU Here]/Rig Build
- Most efficient (hash/watt) hashrate [Insert GPU Here]/Rig Build
- Clock speeds, TDP, etc. for top leaders

**Comment by BobbyGR** [comment]
This seems to be the consensus.  Starting the rebuild of AIOMiner to support this
