### ISSUE TITLE
Cuda OUT of MEMORY?

### ISSUE THREAD

**Issue by gator6615** [BobbyGR/AIOMiner#80]
8.2.2 working fine now it errors out with that message no matter what algo is used?

**Comment by BobbyGR** [comment]
What are you mining?  
What cards do you have?  
What's the memory size on those cards?
What is your page file set to? 

Most likely this is your page file.  You want to increase this to be at least 16GB
https://www.thewindowsclub.com/increase-page-file-size-virtual-memory-windows

**Comment by BobbyGR** [comment]
Any Update?

**Comment by gator6615** [comment]
I'll try that I thought I had it at 8 gigs?

**Comment by BobbyGR** [comment]
16GB is the minimum.  I go for 20-32

**Comment by BobbyGR** [comment]
Any update?

**Comment by BobbyGR** [comment]
closing
