### ISSUE TITLE
No payout in Vertcoin

### ISSUE THREAD

**Issue by bagleyed2** [BobbyGR/AIOMiner#83]
stratum+tcp://us-east.vtc.bitpoolmining.com  The default pool for Vertcoin is not paying for mining, two days and thousands of shares and still no release to the wallet. What is their pay minimum? I can't find much info on them. Thanks. Love what you've done with AIO!

**Comment by BobbyGR** [comment]
Check out bitpoolmining.com , looks like they havent hit a block for vertcoin in the past 24 hours.  While we can make a suggestion on what pool to hit, some times the pool just doesnt have enough power to crack blocks.  Hit them up and see what the estimated crack time is.  It might take you a day or two, but the payout will be larger.  Or like me and 2miners, you could mine for days and get nothing.  If you find a better pool, let me know and I'll add it in

**Comment by bagleyed2** [comment]
Thanks
