### ISSUE TITLE
AIOMiner 9

### ISSUE THREAD

**Issue by BobbyGR** [BobbyGR/AIOMiner#84]
- Overclock Support (amd/nvidia)
- New GUI
- Website Monitoring
- API Support
- Remove Settings.json 
- Website changes
- Apple/Andriod store
- Allow optional donations

**Comment by BobbyGR** [comment]
Implement a new way to test pools.  this will be for the website and the application.
Passed:
`
node test.js
Starting AIOMiner Stratum Check:
Connected! Asking for a Subscriber
 Subscriber Sent!
Mining data: result =  { id: 1,
  result: [ 'deadbeefcafebabeafeb000000000000', '520009ac' ],
  error: null }
Asking for authorization
Mining data: result =  { id: 1,
  result: [ 'deadbeefcafebabeafeb000000000000', '520009ac' ],
  error: null }
Asking for authorization
Mining data: result =  { id: 1,
  result: [ 'deadbeefcafebabeafeb000000000000', '520009ac' ],
  error: null }
We are authorized
Pool Test has passed
`

Failed:
`node test.js
Starting AIOMiner Stratum Check:
Error: Connection closed`

**Comment by kostik1365** [comment]
как вставить ?

**Comment by BobbyGR** [comment]
теперь нет, но с aio9

**Comment by kostik1365** [comment]
мне нужно разобраться что это aio9 в общем я учусь ....

**Comment by BobbyGR** [comment]
sleduyushchaya versiya AIOMiner, ne vypushchennaya. v nastoyashcheye vremya

**Comment by BobbyGR** [comment]
Design has started, and working on the API endpoints and testing.  New Design will be a new AIOMiner from scratch and we will piece in what worked with 8 and previous versions and add in more things that we want.  But for now it's just the design/skeleton.

**Comment by mendel3** [comment]
Updates?

**Comment by BobbyGR** [comment]
The design/UI is in the works.   We are focusing on AIOMiner Linux, that actually does a ton of the backend work needed for 9 at the same time.  So it's still going, just the focus was voted on linux for now.
