### ISSUE TITLE
Anyone having trouble with Cryptonight Heavy Algo Coins?

### ISSUE THREAD

**Issue by hanyoonLDA** [BobbyGR/AIOMiner#87]
Using the latest build, used to work fine. Refuses to work now.

Win 10, 7 RX 580s.

**Comment by BobbyGR** [comment]
What errors are you seeing?

**Comment by BobbyGR** [comment]
Noticed we had a few things growing legs on us here.  CastXMR has been removed.
https://wiki.aiominer.com/index.php/Newminerapplication

I have renamed algo's to make them a bit easier to read.  Please update your miner process and let me know if you have any issues

**Comment by BobbyGR** [comment]
Closing out, please bump if needed
