### ISSUE TITLE
WhatToMine seems unreachable

### ISSUE THREAD

**Issue by vRobM** [BobbyGR/AIOMiner#96]
that's in the logs
yet, visiting the website works just fine. Did they change the API on you?

**Comment by BobbyGR** [comment]
I am not seeing this issue on any of my rigs,  can you please confirm you are still having this issue?

**Comment by vRobM** [comment]
confirmed. not sure if this is any other indication, but the startup banner seems to get stuck and trouble connecting to something before the aiominer screen comes up.
Log\ directory is empty.

**Comment by BobbyGR** [comment]
Can you reach https://sassy.aiominer.com/api ? I confirmed with others they are not having issues.  Everything seems to load correctly.  If you can jump in the discord we can further troubleshoot.

**Comment by vRobM** [comment]
Yes, that is reachable in my browser.

**Comment by vRobM** [comment]
I cannot join discord as the invite expired, from /help/discord support menu

**Comment by BobbyGR** [comment]
AIOMiner.com, select help.  I'll update in app.  Ty

**Comment by vRobM** [comment]
Yw, yeah still waiting on timeout to talk in Discord.. ugh

**Comment by BobbyGR** [comment]
Unable to duplicate with others.  Closing out for now
