### ISSUE TITLE
Dial down intensity when memory is overcommited

### ISSUE THREAD

**Issue by vRobM** [BobbyGR/AIOMiner#97]
An easy way to tell is how much onboard GPU memory is being used once the miner starts, if it's too close to max, it will crash and cause screen glitches. The defaults all do this on my R9 380 4GB.

If this happens, the miner should immediately restart with a lower intensity setting by a notch.

I don't see anywhere to set a custom intensity level in the settings ;-/

**Comment by vRobM** [comment]
where is this documented? I don't see how sending the pool your GPU intensity will work. It's a local miner config.
Furthermore, how is one supposed to set that when performing benchmark/miner selection tests?

**Comment by BobbyGR** [comment]
It's not sending the pool the info. This is a setting that is per miner per algorithm.  So it was put here.  You can ask, or click around.  No one has seemed to run into this issue.  Benchmark/Miner selection is there to confirm something works.  It has no input to your profits.

**Comment by vRobM** [comment]
that's exactly the point. if 1000 intensity is too much for the cards, the benchmarks will always glitch and there's no control.
same for the mining, it's not clear where or how that is set so it stops glitching by running out of memory.
this should be a simple thing.

**Comment by BobbyGR** [comment]
Will address in AioMiner 9
