### ISSUE TITLE
VERT mining

### ISSUE THREAD

**Issue by bagleyed2** [BobbyGR/AIOMiner#99]
Trying to mine VERTcoin. PC reboots, think its algo related to Lyra2ReV2. FYI. CryptoDredge 0.18 update is available now. Thanks

**Comment by BobbyGR** [comment]
Please update your miners.  Vertcoin is no longer in lyra2rev2.  You can go-to update settings and update miners/processes.

**Comment by BobbyGR** [comment]
No updated. closing. Please re-open if needed
